### ISSUE TITLE
Can't complete: "Failed to write task"

### ISSUE THREAD

**Issue by botto** [naggie/dstask#1]
Hi, I'm having an issue with my first task, when I type
```dstask done 1```

I get 
![image](https://user-images.githubusercontent.com/175029/54361009-04a05f80-465e-11e9-8984-ce5ec54bc3a6.png)

**Comment by botto** [comment]
Output from repo
```
git status
On branch master
nothing to commit, working tree clean
```

**Comment by naggie** [comment]
Should be fixed in the latest commit. I'll do a release. The problem was that the status directories were created just in time but only all were created when loading all tasks (including resolved)

**Comment by naggie** [comment]
OK, new release available: https://github.com/naggie/dstask/releases/tag/v0.9
I'll set up some CI when I get a chance.....

**Comment by botto** [comment]
Thanks @naggie that worked
