### ISSUE TITLE
Text search is no longer case insensitive

### ISSUE THREAD

**Issue by naggie** [naggie/dstask#102]
It used to be: https://github.com/naggie/dstask/blob/master/task.go#L209

https://github.com/naggie/dstask/pull/97 will take care of that when I switch the filtering mech back.

**Comment by dontlaugh** [comment]
Reproduction https://github.com/gloriousfutureio/dstask/commit/4307376a9629a0bb010bebbd74f172750797c57b

**Comment by naggie** [comment]
Fixed in PR/master
