### ISSUE TITLE
dstask help does not show more information when not inited

### ISSUE THREAD

**Issue by lidaobing** [naggie/dstask#104]
after install dstask, when you run `dstask`, it said that `dstask help` can show more information, but it's not true.

```
$ dstask
Could not find git repository at /Users/lidaobing/.dstask, please clone or create. Try `dstask help` for more information.
$ dstask help
Could not find git repository at /Users/lidaobing/.dstask, please clone or create. Try `dstask help` for more information.
```

**Comment by naggie** [comment]
Thanks, I will fix this in the next release.

**Comment by dontlaugh** [comment]
relates to #8

**Comment by naggie** [comment]
Indeed -- probably #8 is the better fix.

**Comment by naggie** [comment]
Fixed in master -- dstask offers to create the repo before running the command. Help works without an uninitialised repository.
