### ISSUE TITLE
dstask interroperability with legacy non golang platforms

### ISSUE THREAD

**Issue by berryamin** [naggie/dstask#11]
Hello,

    I'm working on an old platform with gcc 4.8.3 .. Not much chance to have a newer version, cause it's QNX/bb10 . I want to switch from taskwarrior to dstask due to the git support and lack of ssl support for task on my platform as of today, which restricts taskwarrior to non "distributed" tasks.

   Is there a specific, more or less stable format for the information dstask stores in git ? so that I can imagine implementing another dstask client, not based on golang ?

Olivier

**Comment by naggie** [comment]
Yes, and it's unlikely to change much before version 1.0 so it's relatively stable. It will change to support recurring tasks, deadlines etc.

The format on disk stores the tasks in a directory according to the task status, with each task stored under a yaml file with a UUID4 as the filename. The yaml schema is defined by this Go struct: https://github.com/naggie/dstask/blob/c00bc97c3f0132f1d291fdbe33dfb06e02ca6ef6/task.go#L18

This way only non-resolved tasks are actually loaded for most commands, so performance is stable even with a large task history.

The ID presented to the user is simply a sequential ID. IDs are re-used when tasks are resolved; tasks store their preferred ID for consistency across different systems.

I'll update the readme with this information.

**Comment by berryamin** [comment]
@naggie Thank you very much. It will help for dstask adoption I think :-)
When something gets out of this, I'll let you know.

**Comment by naggie** [comment]
Closed due to inactivity
