### ISSUE TITLE
Message when deleting tasks

### ISSUE THREAD

**Issue by cgardner** [naggie/dstask#114]
I was deleting some tasks and noticed that when I delete a task, it tells me that it's going to delete 108 tasks, but only deletes the tasks I've requested.

![image](https://user-images.githubusercontent.com/39611/105546065-bd4f7500-5cb1-11eb-9c1f-b5841f8f4a30.png)

**Comment by naggie** [comment]
huh, you're right. We better fix that. Thanks

**Comment by naggie** [comment]
![image](https://user-images.githubusercontent.com/208440/105579262-5c8d6e80-5d7d-11eb-9d0a-5a24f3cd441a.png)
Fixed in master.
