### ISSUE TITLE
Encode (part of) task ID and Summary in editor tempfile name

### ISSUE THREAD

**Issue by dontlaugh** [naggie/dstask#117]
I often have an editor buffer open for a long period of time, or I leave the terminal and come back and it's been open for a while.

Most editors display the name of the open file. Currently, if I do `dstask edit 1`, the name is mostly random:

```
/tmp/dstask.12345231.tmp
```

I think encoding a fixed-width portion of the ID and Summary could be useful. So the above, for ID 1 and a Summary "Email Bobby about birthday party" could be edited with a temp file like

```
/tmp/dstask.1_email_bobby_ab.12345231.tmp
```

**Comment by naggie** [comment]
hm, sure -- good idea :+1:
