### ISSUE TITLE
Using "/" notation to add notes to a new task with a template doesn't work.

### ISSUE THREAD

**Issue by cgardner** [naggie/dstask#128]
I found out that creating a task with a template and notes doesn't add the notes passed in from the command line.

```bash
dstask add "Test Task" template:123 / This should be a note
```

I could see this as acceptable if the template has default note, but it's for all templates.

**Comment by naggie** [comment]
Ah yes, quite right. Please go ahead and if it if you have time, with a unit test in `cmdline_test.go`
