### ISSUE TITLE
assets in release page have duplicated names

### ISSUE THREAD

**Issue by marco-m-pix4d** [naggie/dstask#131]
hello, thanks for dstask!
I noticed the following in the latest release page https://github.com/naggie/dstask/releases/tag/v0.24.1:

![dstask](https://user-images.githubusercontent.com/51477941/111140935-34530c80-8583-11eb-861d-459f785ce118.png)

**Comment by naggie** [comment]
Oh, they do -- must have been my release script. Thanks, I'll fix it.

**Comment by naggie** [comment]
Fixed, the release has been updated. https://github.com/naggie/dstask/releases/tag/v0.24.1

**Comment by marco-m-pix4d** [comment]
thanks!
