### ISSUE TITLE
Don't use global settings

### ISSUE THREAD

**Issue by ghost** [naggie/dstask#136]
Is it possible to use per directory project settings? That is: storing several dstask's tasks in directories `foo` and `bar` for example

**Comment by naggie** [comment]
It is! Using direnv. See https://github.com/naggie/dstask/issues/20 for discussion.

https://direnv.net/

Currently there are 2 environment variables you can set to override the context and database location: https://github.com/naggie/dstask/blob/master/config.go#L26-L27


I (or anyone) need to get round to updating the README to say this.
