### ISSUE TITLE
Can I configure the path of the database?

### ISSUE THREAD

**Issue by stianlagstad** [naggie/dstask#14]
Can I configure the path of the database to something other than ~/.dstask?

**Comment by stianlagstad** [comment]
Or configure the database for a specific command? One use case is that I would have my work tasks in a separate git repository than my personal tasks, and I'd setup aliases to easily work with both (e.g. `alias tw="dtask.... work"` and `alias tp="dtask.... personal"`).

**Comment by naggie** [comment]
Yes, with `DSTASK_GIT_REPO` as an environment variable. I suppose you could make an alias/wrapper to do set that as you say

**Comment by stianlagstad** [comment]
Thanks! Want me to create a small PR to add that to the README?

**Comment by naggie** [comment]
Yes please!

**Comment by stianlagstad** [comment]
Created #15 . Closing this issue. Thanks for the fast reply!
