### ISSUE TITLE
Remove task warning message incorrectly states all tasks will be removed

### ISSUE THREAD

**Issue by kingo55** [naggie/dstask#140]
When you remove a task, `dstask` says it will remove all tasks. However it only removes the one task you specify:

```
$ dstask rm 52
52: How we use Snowplow Analytics for tracking experiments

The above 39 task(s) will be deleted without checking subtasks. Continue? [y/n] y

Removed: 52: How we use Snowplow Analytics for tracking experiments
[master 4fb4287] Removed: 52: How we use Snowplow Analytics for tracking experiments
 1 file changed, 12 deletions(-)
 delete mode 100644 pending/9f9fd31a-3935-47da-a27f-4af2b9a28ccd.yml
```

In this example above, it says it will remove all 39 tasks rather than just 1 specified task.

It's caught me off-guard a few times...

**Comment by naggie** [comment]
Hi @kingo55, thanks for the report.

It seems this is [fixed in master](https://github.com/naggie/dstask/commit/2bb7d60d00c60ff40ca2158852ddbed90c9c2d6f) -- I'll make a release soon to resolve this.

Callan
