### ISSUE TITLE
Feature: globbing in context

### ISSUE THREAD

**Issue by psprint** [naggie/dstask#144]
Hi,
I'm using tags like "inter" and "inter_me" to mark that a feature of a project is interesting or mostly interesting for me. I would then want to show a list of tags that's just "interesting", regardless if it's "normal" or "private" (ie. for me only) interest. How could I do this?

I thought about supporting a glob star, ie. to make `dstask +inter*` work. Could such feature be added?

**Comment by naggie** [comment]
I suggest you use 2 separate tags, `+inter` and `+me` -- globbing on tags is not something I want support. 

Callan

**Comment by cgardner** [comment]
Alternatively, you can use `jq` to filter the results however you want.

`dstask | jq -r '.[] | select(.tags[] | contains("inter")) | "\(.id)\t\(.summary)"'`
