### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by yerlaser** [naggie/dstask#147]
Do you plan to release a Windows version at some point?
If not, what are the blockers?

**Comment by dontlaugh** [comment]
I think someone with a Windows machine needs to test the behavior on Windows Subsystem for Linux (WSL). If we're note using cgo, it should build fine.

I think adopting a library that handles Windows, Mac, BSDs, and Linux "user config dirs" might be the most elegant way to support it see #49  . The dstask database is a directory tree, and those are obviously different on Windows. The Go std library does have the `filepath` module, however, which can paper over the path separator differences.

**Comment by yerlaser** [comment]
WSL will almost surely work, however, the original Windows support would be ideal.
But, yes, if you use cgo libraries those will likely be blockers.
Let's keep this issue open, maybe someone will have an idea at some point on how to move forward.
