### ISSUE TITLE
Is there any todo utility that supports importing DStask yml database?

### ISSUE THREAD

**Issue by psprint** [naggie/dstask#148]
Could you maybe help me? Do you know of any such todo tool?

Or maybe DSTask supports exporting to some popular format?

**Comment by naggie** [comment]
There's probably nothing that can currently import a dstask database, but dstask is designed to make it very easy to extract data if you want to migrate away.

For YAML, the git repository that dstask uses is just a small hierarchy of yaml files, one per task -- check out the `~/.dstask` git repository after making a few tasks. 

For JSON, dstask will automatically output json if it thinks it isn't outputting into a terminal.

````bash
dstask show-resolved > resolved.json
dstask show-active > active.json

````
...will cover all bases.
