### ISSUE TITLE
Critical task count for warning counts templates but should not

### ISSUE THREAD

**Issue by bongoman** [naggie/dstask#151]
I created a template task with P0

When I run the `dstask` report, I get the warning: "1 critical tasks outside this context! Use `dstask -- P0` to see them."

When I run `dstask -- P0` I receive the output: "No matching tasks in given context or filter."

How to view the P0 task?

**Comment by kingo55** [comment]
That's odd - it should work. How about if you go?:

```bash
dstask context --
dstask P0
```

**Comment by naggie** [comment]
It seems that count includes templates, where it should not.
