### ISSUE TITLE
GitHub repo import vs sync

### ISSUE THREAD

**Issue by dixonge** [naggie/dstask#153]
I successfully imported from GitHub, but have run into these problems:

1. Issues imported as tasks, but the task lists inside the issues do not seem to be imported. Is this the expected behavior?
2. If not, is there any way to bulk modify in dstask to make task summaries into project names?
3. Which repo is the git sync feature supposed to work with? The one imported from, or a separate one?

**Comment by naggie** [comment]
1. They should be in the task note
2. No, however json output is available if you use a shell pipeline
3. A separate one, usually; so long as it's dedicated.
