### ISSUE TITLE
dstask *-completion broken in v0.25

### ISSUE THREAD

**Issue by axelsimon** [naggie/dstask#169]
Using the latest v0.25, it appears the completion commands are broken:

```
$ dstask bash-completion
No matching tasks in given context or filter.
```

```
$ dstask zsh-completion
No matching tasks in given context or filter.
```

Which means they'll make sourcing a `.bashrc` that refers to them throw an error. And of course, means you don't get completion, which is pretty annoying as it means having to type out tags completely, every time :)

**Comment by dontlaugh** [comment]
Those subcommands are technically unreleased. If you can compile from `master`, give it a shot.

If not, copy and source the completion scripts directly. See here https://github.com/naggie/dstask/tree/7dec81f14c1b7251b24d4d720b5351ae8d276479#installation

Or contact the packager for your distribution and ask if/how the completion scripts are shipped with dstask.

@naggie any blockers for a release?

**Comment by axelsimon** [comment]
Thanks for your answer and help, @dontlaugh.

Considering those commands are in step 2 of the install instructions
> 2. Enable bash completions by copying source <(dstask bash-completion) into your .bashrc. There's also a zsh-completion subcommand.

I'm inclined to say it's hard to argue they are unreleased: install instructions tell you to use them.
That being said, i hear what you are saying, and if they are currently not considered released, then maybe the README should be amended to reflect that.
In any case, I'll grab the bash completion script from the repo, thanks.

**Comment by naggie** [comment]
I'll roll a release now -- sorry swamped at the moment!

**Comment by naggie** [comment]
Done! https://github.com/naggie/dstask/releases/tag/v0.26

Wow, didn't realise I had so much waiting on master...

**Comment by axelsimon** [comment]
Thanks @naggie !
