### ISSUE TITLE
Is there a way to modify the color settings?

### ISSUE THREAD

**Issue by spfeifer222** [naggie/dstask#17]
Aloha again,

Because red or orange on black is very alarming to me, I like to change the priority colors. Is there a way to pass such settings?

Best regards,
Sebastian

**Comment by naggie** [comment]
> Because red or orange on black is very alarming to me
They're meant to be :-)

I was waiting for the day someone would ask for customisable colours. I think it's a reasonable request. I think I'll add a configuration file to allow this, probably created automatically if it does not exist.

**Comment by spfeifer222** [comment]
Thanks a lot & take care of yourself (in these times)!

**Comment by naggie** [comment]
You're welcome -- thanks, you too.

**Comment by spfeifer222** [comment]
What kind of color code is this 3-digit syntax?

**Comment by naggie** [comment]
They are from the xterm 256 colour palette, here's a good reference https://commons.wikimedia.org/wiki/File:Xterm_256color_chart.svg

In you come up with a good theme please post it here, perhaps it could be distributed with dstask.

**Comment by spfeifer222** [comment]
Thanks for the reference. Goos is some kind of subjective, but sure I will post it! 

So we are going into the details: I installed dstask by downloading the executable like suggested. Beside the task data, this is the only file from dstask itself. So how I am going to make this working with values in the file https://github.com/naggie/dstask/blob/master/const.go#L83 ?

**Comment by naggie** [comment]
That link is to a go source file, sorry I should have explicitly said it would require recompilation of dstask, as dstask has no way of loading configuration from a file at runtime at the moment -- the current binary download has a fixed palette. 

To get a custom build of dstask in order to customise the colours:

1. Install the latest golang
2. clone the dstask repository with git
3. cd into `dstask`
4. edit `dstask/const.go`
5 run `go build cmd/dstask.go`

The resulting custom exe will be in your current working directory.

**Comment by spfeifer222** [comment]
- [x]  `sudo apt install golang` installed the latest `golang` supported by my distribution: version __2:1.10~4ubuntu1__ 
- [x] `git clone https://github.com/naggie/dstask.git` successful
- [x] `dstask/const.go` edited
- [ ] `go build cmd/dstask.go` failed:

```bash
(base) pfeifer@LP ~/dev/dstask/ go build cmd/dstask.go
cmd/dstask.go:10:2: cannot find package "github.com/mvdan/xurls" in any of:
	/usr/lib/go-1.10/src/github.com/mvdan/xurls (from $GOROOT)
	/home/pfeifer/go/src/github.com/mvdan/xurls (from $GOPATH)
cmd/dstask.go:11:2: cannot find package "github.com/naggie/dstask" in any of:
	/usr/lib/go-1.10/src/github.com/naggie/dstask (from $GOROOT)
	/home/pfeifer/go/src/github.com/naggie/dstask (from $GOPATH)
cmd/dstask.go:12:2: cannot find package "gopkg.in/yaml.v2" in any of:
	/usr/lib/go-1.10/src/gopkg.in/yaml.v2 (from $GOROOT)
	/home/pfeifer/go/src/gopkg.in/yaml.v2 (from $GOPATH)
```
What do you suggest?

**Comment by naggie** [comment]
That's' not the latest golang, which is required for module support. You can get the latest golang binaries here: https://golang.org/dl/ . Make sure you remove the old first.

**Comment by spfeifer222** [comment]
- [x] `go version go1.14.2 linux/amd64` installed
- [x] build
    - [ ] failed with line `BG_ACTIVE = 028`: `./const.go:88:27: invalid digit '8' in octal literal`
    - [x] build completed with line `BG_ACTIVE = 022` (a different green) 

However, I played around and the green is not used at the moment. See screenshot in attachment!

What about `TABLE_MAX_WIDTH` ? I raised that value in order to use complete terminal width, but it apears to have no effect.
![Bildschirmfoto zu 2020-05-04 10-31-10_cut](https://user-images.githubusercontent.com/46728699/80948947-5f14f600-8df3-11ea-8e44-83d6b06f347f.jpg)

------

**Comment by naggie** [comment]
> What about TABLE_MAX_WIDTH ? I raised that value in order to use complete terminal width, but it apears to have no effect.

The table expands to the size of the content, limited by TABLE_MAX_WIDTH

> BG_ACTIVE = 028: ./const.go:88:27: invalid digit '8' in octal literal

Remove the leading zero, that makes it an octal number.


The active colour is used if you start a task: `dstask start 6` for instance.

**Comment by spfeifer222** [comment]
Allright. Thanks again. I will send you the final color settings, but I think I need some time to experience.

**Comment by vanarok** [comment]
How to get color number from "#F06565" for const.go? Unclear.
