### ISSUE TITLE
match package versions between GitHub and pkg.go.dev

### ISSUE THREAD

**Issue by playonverbs** [naggie/dstask#185]
The latest available tagged version on GitHub is v0.26 while the latest version listed on pkg.go.dev (https://pkg.go.dev/github.com/naggie/dstask@v0.24.1) is v0.24.1.

There are several API differences between the binary that users may have installed and the available go library when trying to add dstask to other go projects. Could the pkg.go.dev version be updated to v0.26 please?

**Comment by naggie** [comment]
pkg.go.dev updates directly from github. As it turns out, it wasn't updating because it was expecting a different format for the version. I've since added a `.0` to the version name and it's updated. Thanks for reporting!
