### ISSUE TITLE
Behaviour of `dstask next`

### ISSUE THREAD

**Issue by twan163** [naggie/dstask#187]
I have been using `dstask` for a couple of years now and am quite happy with it, if it weren't for the default way in which the list of tasks is displayed when entering the `dstask` command.

Apparently, the default behaviour of the `dstask` command on my system (Linux Fedora 39) is to first display the list of tasks (no context set), *followed by the details of all the tasks with `P0` priority*. The problem with this approach is that I always have to scroll up to see an overview of the tasks of e.g. priority `P1`, because they are pushed off the top of the screen. 
Even when filtering on specific tasks, unrelated to priority `P0`, the list of tasks is correct, but the appending of detailed `P0` tasks is still happening.

I  have taken a close look at the help instructions, but I am overlooking something obvious, I guess.

Is there a setting that changes the behaviour of `dstask` to only display an overview of tasks, without being followed by the details of the `P0` tasks?

**Comment by naggie** [comment]
Hi @twan163 that's definitely a bug. What version are you using?

**Comment by twan163** [comment]
Hi, I am on version 0.26

**Comment by naggie** [comment]
Ok -- fixed -- there was a debug call to `.Display()` left in. Thanks for the report!
