### ISSUE TITLE
Building dstask for NixOS?

### ISSUE THREAD

**Issue by stianlagstad** [naggie/dstask#19]
I've been trying to get dstask working with NixOS. See my efforts here:
- [PR to NixOS adding dstask](https://github.com/NixOS/nixpkgs/pull/87383)
- [Question on the NixOS discourse about help building a Golang package for NixOS](https://discourse.nixos.org/t/help-building-a-go-package/7117/4)

I'm not comfortable building Go packages so I thought I'd ask: Do you see anything specific that I'm doing wrong?

**Comment by naggie** [comment]
You're doing nothing wrong/strange. If you were building outside of nixos it's a simple clone and `go build cmd/dstask.go`.

I've had a look at the conversation, and it looks like the golang builder for nixOS doesn't allow customising the subpackage executable name. By default, if you run `go build cmd/dstask.go`, at least on the latest `go`, it produces an executable called `dstask`. 

I think we have 2 options:

1. Add a command to rename the produced exe (which is apparently called `cmd`) but I'm not sure that's possible with the builder.  Maybe something like an `installPhase`?
2. I could also just rename the `cmd` directory to `dstask` but that feels like a hack 

By the way, I think the `modSha256` variable is probably something like the hash of `go.sum` which contains hashes of the checkouts of dependencies defined in `go.mod`.

I've been meaning to try NixOS, this will give me incentive to try it. Thanks!

**Comment by foxit64** [comment]
@stianlagstad 
I did the same thing a few days ago! :) This is my default.nix:
```nix
{ lib, buildGoModule, fetchFromGitHub }:

buildGoModule rec {
  pname = "dstask";
  version = "v0.18";
  rev = "d687a0f9aec634a808cfa0df4aecb06ab4f57732";

  subPackages = [ "cmd/dstask.go" ];

  src = fetchFromGitHub {
    owner = "naggie";
    repo = "dstask";
    rev = "${version}";
    sha256 = "16z5zlfj955pzsj0l58835slvpchdaq2vbyx2fjzi6y9xn1z2nd1";
  };

  modSha256 = "1ydzqg8p2d514sdb34b2p6k1474nr1drrn3gay2cpyhrj5l51cj3";

  buildFlagsArray = [ ''-ldflags=-w -s
    -X "github.com/naggie/dstask.VERSION=${version}"
    -X "github.com/naggie/dstask.GIT_COMMIT=${rev}"
  '' ];

  meta = with lib; {
    description = "A personal task tracker designed to help you focus";
    license = licenses.mit;
    homepage = "https://github.com/naggie/dstask";
    maintainers = with maintainers; [ foxit64 ];
  };

}
```

**Comment by naggie** [comment]
Thanks @foxit64 -- I'm glad you remembered the build flags, I forgot about those.

@stianlagstad are you happy to update your PR to Nix?

**Comment by stianlagstad** [comment]
Thanks @naggie and @foxit64 ! I'll go ahead and update the PR.

**Comment by stianlagstad** [comment]
PR updated: https://github.com/NixOS/nixpkgs/pull/87383

I added us both as maintainers, @foxit64 - hope that's ok.

**Comment by foxit64** [comment]
Sure, that's great.

**Comment by naggie** [comment]
Thanks both! I ended up renaming `cmd/` to `dstask/` as that appears to be what most go projects do to produce an installed binary via go get/install.

**Comment by foxit64** [comment]
It happened! "dstask" is now a part of something bigger!

**Comment by stianlagstad** [comment]
Thank you for the effort! Looking forward to using dstask again :)
