### ISSUE TITLE
Multiple Active Context

### ISSUE THREAD

**Issue by ChicK00o** [naggie/dstask#20]
So using iterm, i would like to keep different context in different window, to use it as different active boards to work on, any ideas on this.
Tried doing it, but changing the context changes it globally across different iterm planes

**Comment by naggie** [comment]
The only way you can currently do this is to use a different repository per tab. You could have a bash script in your bashrc that sets the dstask repo location based on the git project, for instance. The environment variable is `DSTASK_GIT_REPO`

I have considered allowing a `.dstask-context` file that dstask will search for to set context based on project, or an environment variable to set context. I'm not sure at the moment.

**Comment by stianlagstad** [comment]
Setting the `DSTASK_GIT_REPO` using https://direnv.net/ could be a solution.

**Comment by naggie** [comment]
Thinking about it, I think `envdir` plus a new environment variable, `DSTASK_CONTEXT_OVERRIDE` or something could be a nice solution. I'll leave this open as I will implement it.

**Comment by dontlaugh** [comment]
Working on a version of this in #66

**Comment by dontlaugh** [comment]
If anyone is willing to build from the master branch, context can now be set/overridden with the `DSTASK_CONTEXT` environment variable. For example: `export DSTASK_CONTEXT="+work -waiting"`

**Comment by naggie** [comment]
Actually it's built into v0.23.1 -- I forgot to add that to the release note, sorry! I've amended the release note. https://github.com/naggie/dstask/releases/tag/v0.23.1

**Comment by Dieterbe** [comment]
looks like this can be closed.
