### ISSUE TITLE
Export Script

### ISSUE THREAD

**Issue by sliptonic** [naggie/dstask#21]
dstask should support export to the same taskwarrior json format that it supports for import.  This would make it possible to move between applications more easily.  It would also make it easier for people to try out dstask without fear that they'll be stuck.

**Comment by naggie** [comment]
Unfortunately this would be a lossy process at the moment, unless we support all taskwarrior tasks data features. I'll take a look soon though

**Comment by naggie** [comment]
I don't think it makes sense to do this given it would be lossy. Most commands pipe JSON if used in a pipeline, and the database is just yaml so it should be quite easy to script a solution if you really need it.
