### ISSUE TITLE
Where is context set in the environment?

### ISSUE THREAD

**Issue by dontlaugh** [naggie/dstask#24]
I've got a little shell function that combines `entr` and `fd-find` to clear the screen and reload a task list every time I add or modify a task.

```sh
tasklist () {
	while true
	do
		fd -g '*.*' ~/.dstask | entr -cd dstask
		code=$? 
		if [[ $code == 130 ]] || [[ $code == 143 ]]
		then
			return 1
		fi
		sleep 1
	done
}
```

Changing context doesn't reload the list, though. Is there a file I can watch on disk somewhere with `entr`?

**Comment by naggie** [comment]
The state file, which contains the context is in `~/.dstask/.git/dstask/state.bin`. See https://github.com/naggie/dstask/blob/master/const.go#L189 for reasoning.

I hadn't heard of `entr`, so thanks -- I had been using inotify-tools which is a bit long-winded.

**Comment by dontlaugh** [comment]
ah makes sense. `fd` ignores hidden directories by default.

**Comment by dontlaugh** [comment]
This answers my question. Feel free to close, if you like :+1:
