### ISSUE TITLE
View markdown notes without editing

### ISSUE THREAD

**Issue by dontlaugh** [naggie/dstask#25]
Sometimes it is nice to be able to print the markdown notes to a file like this:

```
dstask note 4 > output.md
```

Looking at the code here, it doesn't seem to be possible yet https://github.com/naggie/dstask/blob/master/cmd/dstask.go#L224

`dstask` could check if stdout is a tty, and if it is not, simply write the markdown to stdout. Otherwise, if the output is a tty, open a copy of the note in the $EDITOR (the current behavior).

**Comment by naggie** [comment]
Actually I had planned that exact thing, except the issue is tracked on my local dstask haha. I should probably transfer them all to github.

I'll get round to it soon as I think it's a useful feature.

**Comment by dontlaugh** [comment]
#27 should have fixed this. Reopen if there's a bug.
