### ISSUE TITLE
Add copy command

### ISSUE THREAD

**Issue by ard0gg** [naggie/dstask#29]
I would like to create some template tasks that have some some generic process steps in the notes. 
This would be used for complex tasks that might be repeated for different projects (like a release checklist)

Assuming my template task were numbered 16, I imagine the command would look something like: 
`dstask copy 16 This is the description of the new task copied from 16 `

**Comment by ard0gg** [comment]
Perhaps this command would be better:
`dstask 16 copy ....`

**Comment by dontlaugh** [comment]
I like the motivation here, however there are some subtle complexities to a `copy` command. Specifically, projects, priorities, tags. Should these things be copied, as well? What is right for one user might not be right for another. This is where I would, personally, write a script that suits my needs.

But we have a problem. Even if we do not make a dedicated `copy` command, as it stands the default `task N` command will complain about stdout not being a terminal. This is similar to the issue in #25 

Therefore, it is **not yet** possible to write a copy function like this, which could be a version of what you want:

```sh
copytask () {
  local taskid=$1
  summary=$(dstask $taskid | awk '/^Summary/ { $1=""; $0=$0; } NF=NF')
  task add $summary
}
```
We should, at the very least, enable a scripting use case. Scriptability was what enabled taskwarrior to develop a rich and interesting ecosystem.

I will defer to naggie on what should or should not be in core.

**Comment by ard0gg** [comment]
A script could work just as well. 
I would expect that and projects, priorities, tags would be copied by default, but additional modifiers in the command line would modify the copied task as necessary. I would expect that it would be sort of  CMD_ADD followed by a CMD_MODIFY. 

Excuse my coding. I'm not a strong programmer. So there's some psuedo-code 

```golang
case dstask.CMD_COPY:

                // add some logic to parse cmdLine.IDs and verify just one and that it's valid
             

		originalTask := dstask.LoadTasksFromDisk(dstask.NON_RESOLVED_STATUSES).mustgetbyid(id)

		context.PrintContextDescription()  
		cmdLine.MergeContext(context)
		task := dstask.Task{
			WritePending: true,
			Status:       dstask.STATUS_PENDING,
			Summary:      originalTask.Text+" - COPY" ,  //default summary text to append "- COPY"
			Tags:         originalTask.Tags,
			Project:      originalTask.Project,
			Priority:     originalTask.Priority,
			Notes:        originalTask.Note,
		}
			task = ts.LoadTask(task)
                        
                        // modify cmdline.IDs to remove originalTaskID and replace with task ID
                        // cmdLine.IDs = {task.ID} ??
                         
                        task.Modify(cmdLine)
			ts.MustUpdateTask(task)
			ts.SavePendingChanges()
			dstask.MustGitCommit("Added %s", task)
		
```

**Comment by naggie** [comment]
I've thought about achieving the same end with "template" tasks before. I think they should be stored and accessed separately from regular tasks to prevent polluting the normal view.

For instance, something like:

* `dstask template` could create a template (with a regular UUID and cached numeric ID)
* `dstask edit 34` (for instance) could be used to edit the template as normal
* `dstask add template:34 ...` could create a new task with the template

Either that, or the note command could accept input from stdin, though there are some complications with that now that you can [pipe notes out](https://github.com/naggie/dstask/pull/27) of the note command without firing up the editor.

Does that sound reasonable?

**Comment by ard0gg** [comment]
That would make sense as well. How would one view/list all template tasks in this case? `dstask show-templates`?

The way I handled this in TW is to add the +template tag to a task, then include a -template to the context, but then every context would need a -template, so I do like the idea of having a separate storage just for templates.

**Comment by naggie** [comment]
Yes exactly -- forgot to add that, I've edited for completeness. The template tag is a good workaround but yes I agree it would make contexts awkward.

**Comment by ard0gg** [comment]
I assume this would have a similar data model to what you've already done for recursive tasks?

**Comment by naggie** [comment]
Yes, so the tasks would be the same in the database, but in a `templates/` directory.

**Comment by naggie** [comment]
Now in master
