### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by burner** [naggie/dstask#3]
I'm lazy and modify, next, add, undo is so much to type.

What about some one letter shortcuts?

**Comment by naggie** [comment]
I suggest you install the bash (or zsh) completions: https://github.com/naggie/dstask/blob/master/.dstask-bash-completions.sh

That way you can complete commands, tags, projects etc.

**Comment by burner** [comment]
okay

**Comment by naggie** [comment]
I also have an alias in my bashrc : `alias t=dstask`
