### ISSUE TITLE
ZSH Tab completion not working on negative tags

### ISSUE THREAD

**Issue by kingo55** [naggie/dstask#35]
Really liking dstask - been using it for a couple of months now!

I've just found an issue where tab completion for tags works when using `+ta` -> `+tagname` but it doesn't work when you change the operand to `-` e.g. `-ta` does not resolve to `-tagname`.

Pretty minor issue though.

**Comment by ard0gg** [comment]
Do you have a context set? What happens if you ignore context `--` before trying to enter a tag and perform completion?

**Comment by ard0gg** [comment]
Also what version are you running? I can only partially replicate the issue. The only time I cannot complete tags is when I have a context set that does not include the tag. But it applies to the `+` and `-`.

**Comment by kingo55** [comment]
Thanks for checking out so quickly. 

I'm still running `0.18` in MacOS/zsh/ohmyzsh and am not using contexts yet:

```
$ dstask context
Current context: %     
```

Tab completion works without `-` e.g.:

```
robertkingston@MacBook-Pro ~ $ dstask
+####           +mojito           +####              -mint             -personal         P1                add               edit              import-tw         next              open              show-next         show-projects     show-unorganised  sync
+####          +####      -####           -mojito           -####              P2                context           git               log               note              resolve           show-open         show-resolved     start             undo
+mint             +personal         -####          -####      P0                P3                done              help              modify            notes             show-active       show-paused       show-tags         stop              version
```

When I attempt tab completion after typing `dstask -m`, I get "bad option" errors:

```
robertkingston@MacBook-Pro ~ $ dstask -m
_dstask:compadd:1: bad option: -m
_dstask:compadd:1: bad option: -m
_dstask:compadd:1: bad option: -m
```

If I attempt tab completion after `dstask -p`, nothing shows up:

```
robertkingston@MacBook-Pro ~ $ dstask -p
```

And if I execute `dstask -p` or `dstask -q` then for some reason it shows a task I have pending:

```
robertkingston@MacBook-Pro ~ $ dstask -p
Name      Value
ID        35
Priority  P3
Summary   Create contextual analytics tool
Status    pending
Project
Tags      mint
UUID      8a9335b3-a19a-4b94-a78f-cbdbbba02a91
Created   2020-07-20 15:11:59.091628 +1000 AEST

Notes on task 35:
Use Superset to expose page metrics in-page
```

Certainly not a deal breaking issue.

**Comment by naggie** [comment]
I can confirm that I get this too, using my fairly standard ZSH shell:
<img width="250" alt="image" src="https://user-images.githubusercontent.com/208440/89075591-745bdb00-d376-11ea-80a0-1b3cd795d868.png">


It's fine on bash though. Will investigate when I get time. Thanks for the report.

**Comment by naggie** [comment]
This is now fixed in master -- I've added the `--` to compadd which makes zsh treat what dstask produces as plain words; dstask can only do basic completions with no elaboration.

From http://zsh.sourceforge.net/Doc/Release/Completion-Widgets.html
```
--

    This flag ends the list of flags and options. All arguments after it will be taken as the words to use as matches even if they begin with hyphens.
```

**Comment by naggie** [comment]
Fixed in release v0.22 https://github.com/naggie/dstask/releases/tag/v0.22

**Comment by naggie** [comment]
> Do you have a context set? What happens if you ignore context `--` before trying to enter a tag and perform completion?

Ha, I just realised @ard0gg had the solution all along. Oops :)

**Comment by kingo55** [comment]
If only I tested `--` in the prompt and not just `dstask --` before testing. 🤦 

Either way, thanks for the fix guys!

**Comment by naggie** [comment]
Oh, I now realies @ard0gg meant `--` as a dstask parameter not a `compadd` parameter. Coincidence!
