### ISSUE TITLE
Quickstart documentation for a golang newbie ?

### ISSUE THREAD

**Issue by berryamin** [naggie/dstask#4]
Hello,

  I'm really curious about dstask .. but rather newbie with golang .. Tried the following up to now:
1. sudo apt-get install golang
2. mkdir and setup and GOPATH, GOROOT
3. cd ~/dstask
4. go get       # go fetch all required module to $GOPATH

<pre>
~/dstask$ go get | head
package encoding/gob: unrecognized import path "encoding/gob" (import path does not begin with hostname)
package encoding/json: unrecognized import path "encoding/json" (import path does not begin with hostname)
package errors: unrecognized import path "errors" (import path does not begin with hostname)
package fmt: unrecognized import path "fmt" (import path does not begin with hostname)
package bytes: unrecognized import path "bytes" (import path does not begin with hostname)
package crypto/md5: unrecognized import path "crypto/md5" (import path does not begin with hostname)
package crypto/rand: unrecognized import path "crypto/rand" (import path does not begin with hostname)
package crypto/sha1: unrecognized import path "crypto/sha1" (import path does not begin with hostname)

</pre>

5. go run ./cmd/dstask.go  2>&1 | head

<pre>
~/dstask$ go run ./cmd/dstask.go 2>&1 | head
../gopath/src/gopkg.in/yaml.v2/emitterc.go:4:2: cannot find package "bytes" in any of:
        /home/kalou/goroot/src/bytes (from $GOROOT)
        /home/kalou/gopath/src/bytes (from $GOPATH)
../gopath/src/gopkg.in/yaml.v2/decode.go:4:2: cannot find package "encoding" in any of:
        /home/kalou/goroot/src/encoding (from $GOROOT)
        /home/kalou/gopath/src/encoding (from $GOPATH)
../gopath/src/gopkg.in/yaml.v2/decode.go:5:2: cannot find package "encoding/base64" in any of:
        /home/kalou/goroot/src/encoding/base64 (from $GOROOT)
        /home/kalou/gopath/src/encoding/base64 (from $GOPATH)
../gopath/src/gopkg.in/yaml.v2/yaml.go:10:2: cannot find package "errors" in any of:
</pre>

Any tips on what I should do next ?

**Comment by naggie** [comment]
Hi,

What's your go version?

Though, you don't need to install golang to use dstask, see https://github.com/naggie/dstask#installation -- the releases page allows download of a pre-compiled binary which can be dropped into `/usr/local/bin/` and set executable.

**Comment by berryamin** [comment]
Ho indeed, the binary works great, I'll start my migration from TW in a few days :) Very smart to use git instead of ssl stuff 👍 

I'm using go version go1.7.4 .
Is it a tough job to build from git ?

**Comment by naggie** [comment]
> Ho indeed, the binary works great, I'll start my migration from TW in a few days :) Very smart to use git instead of ssl stuff 

Thank you. 


> I'm using go version go1.7.4 .
> Is it a tough job to build from git ?

It's not hard to do -- you had the right commands but your go installation is too outdated to support go modules which I make use of in dstask.

I suggest you remove your current golang installation, and install a new version following https://golang.org/doc/install -- I find the tar method works well.

**Comment by berryamin** [comment]
Ok thank you very much, I'll do this.
Best Regards

**Comment by naggie** [comment]
Hi @berryamin, I realised that I never set up go modules for this repository (I was using dep). Since then I've switched to go modules, retaining the vendor directory so all dependencies are included.

I've added a Makefile so the standard `make` `sudo make install` commands should work.

**Comment by berryamin** [comment]
Whoow great! I'll give it a try asap
