### ISSUE TITLE
Bulk remove tags

### ISSUE THREAD

**Issue by thatnerdjosh** [naggie/dstask#42]
Given that there doesn’t seem to be an easy way to set dates with keywords such as `today` or `friday` etc... I’ve been using `+today`, `+week`, etc.

It would be nice to be able to make a cron job that would auto remove all the `+today` and `+week` tags, etc. on the relevant interval.

Is this possible using `dstask` or would I need to script it?

EDIT: See `Synonyms` section in https://taskwarrior.org/docs/dates.html

**Comment by naggie** [comment]
Currently there isn't a way. For now a cron job such as:

```
yes | ~/.local/bin/dstask modify -- -today`
```

Would do, scheduled at the correct interval. Note the `yes` command piped into stdin to confirm the message: `No IDs specified. Apply to all 465 tasks in current context? [y/n]`.

As a feature, I think tags probably aren't the way to do it. A better query system and support of due dates might be better. I'll look into it after recurring tasks are implemented for v1.0.

**Comment by NerdsvilleCEO** [comment]
@naggie awesome! For now I am just using a whiteboard :)

**Comment by naggie** [comment]
Actually the `yes | `  is now unnecessary, as the confirmation only happens when a TTY is detected.

**Comment by thatnerdjosh** [comment]
Maybe it would be better to keep the confirmation and add a `-f` flag similar to how commands like `rm` or `cp` work?

**Comment by naggie** [comment]
I don't think it's necessary now this works inside of a script
