### ISSUE TITLE
Go Releaser

### ISSUE THREAD

**Issue by 1995parham** [naggie/dstask#52]
[GoReleaser](https://github.com/goreleaser/goreleaser) is a tool for generating the required binaries in each release and even you can automatically update brew repositories, etc. If you want I can create PR for this.

**Comment by naggie** [comment]
I'm not convinced we need this right now as I'm quite happy with the build process. That said it looks like it could work, for instance, seems like we can inject the version variable with the linker https://github.com/goreleaser/goreleaser/blob/master/.goreleaser.yml#L23


Thanks for bringing it to my attention though! I'll keep it in mind

**Comment by FalcoSuessgott** [comment]
Would love go-releaser releasecylce
@naggie 
I could provide a first PR if you want using github actions
