### ISSUE TITLE
(on filtering refactor, not released versions) searching is broken, task addressing is broken

### ISSUE THREAD

**Issue by naggie** [naggie/dstask#56]
In master, since https://github.com/naggie/dstask/pull/53 searching by keyword is broken.

- [ ] fix task addressing, eg `dstask 23`
- [ ] fix task search eg `task banana`
- [ ] unit test for task addressing
- [ ] unit test for task search

**Comment by dontlaugh** [comment]
I will take a look at this tonight

**Comment by naggie** [comment]
ok, thanks 👍

**Comment by dontlaugh** [comment]
For indexing by ID, what is the desired behavior, exactly? Is it: if an ID is explicitly passed, the task will _not_ be filtered from the result, regardless of context, tags, projects, etc. ?

**Comment by naggie** [comment]
Specifying an ID allows tasks that are out of context to be manipulated: For example, sometimes I search outside the context with `dstask -- project:dstask` or something. Then I might want to close or view a task by ID.

If an ID is passed with filters such as tags or project, that should throw an error. I think that's the most clear way.

**Comment by naggie** [comment]
Tracked as part of https://github.com/naggie/dstask/issues/59
