### ISSUE TITLE
aggregate issues for filtering refactor

### ISSUE THREAD

**Issue by naggie** [naggie/dstask#59]
The filtering refactor here https://github.com/naggie/dstask/pull/53 was merged but later reverted due to significant bugs. I think we're best working on a separate branch/PR until the bugs are fixed and tested

- [ ] task addressing by ID is broken
- [ ] the modify command ignores the ID passed to it and applies the change to every given task. (probably caused by the above)
- [ ] search by keyword is broken

I think given this is a refactor of filtering it would make sense to fix these in this branch too:

- [ ] https://github.com/naggie/dstask/issues/44 task by index not working outside of context
- [ ] https://github.com/naggie/dstask/pull/57 Explicitly passed IDs take precedence over anything (which doesn't yet account for the `modify` command, I think).

We should have unit tests for the above too.

@dontlaugh please could you create a new PR for #56 then we can work on those issues. Thanks

**Comment by dontlaugh** [comment]
Sounds good to me. :+1: I will make sure all these things are taken into account.

**Comment by dontlaugh** [comment]
How are we to determine if a search should be added into our filtering logic?

Is it: if _any_ text is present in the `Text` field of a parsed CmdLine AND if the Cmd is a "read" command (such as "next"), then that text is to be used as a filter? Meaning, any tasks left over after context/tags/projects are filtered, will be further filtered by a search for the `Text` string passed?

**Comment by naggie** [comment]
Yes exactly, text is always part of the filtering logic. It shouldn't be present when using the modify command though.

**Comment by dontlaugh** [comment]
An end-to-end integration test would help prevent these regressions, and might be easier to implement and maintain in the near term. 

Would you mind if I cherry-picked the JSON rendering from #58 and introduced it for the commands that render complete tasks?

* show-active
* show-paused
* show-open
* next (also the default command)
* show-templates
* show-resolved
* show-unorganised

I definitely want unit tests, as well. But unit testing itself requires refactoring. In the meantime, it might be convenient to be able to have a test script like this to watch our backs.

```sh
set -e
dstask add +foo task one
dstask add +baz task two
# a non-zero exit code from diff will signal an error to us.
diff <(dstask) ./integration/testfiles/expected.json
```

As long as our assignment of IDs remains deterministic, this could also work for `modify` as well. 

This would rely on JSON being the default for some commands that simply render output (e.g. "next" and friends). An alternative to making JSON the default in this situation would be controlling JSON output with an environment variable, something like `DSTASK_JSON_OUTPUT=1". We could set this in a script just as easily, like we do with fake pty right now.

**Comment by dontlaugh** [comment]
Oof, I forgot that UUIDs and timestamps complicate this "golden file" approach a lot.

**Comment by naggie** [comment]
Good point about the JSON if it contains the UUIDs for testing. Though, we could just diff existing output I suppose; or better yet strip the UUIDs with a python script for comparison. 

Do you have a reference to the JSON commit? I'd like to see it

**Comment by dontlaugh** [comment]
Here is the branch where I cherry-picked in the JSON output, and added another commit to stub out an **integration** folder. https://github.com/gloriousfutureio/dstask/tree/json_integration_tests

**Comment by naggie** [comment]
Ok, that seems like a good solution. I like how the json output is very little code.

**Comment by dontlaugh** [comment]
@naggie I'll work on the suite of tests first, to give us a target to aim at.

**Comment by dontlaugh** [comment]
In light of #62 I wanted to just enumerate our test coverage.

>  task addressing by ID is broken

[Test is next_id_index_test.go](https://github.com/naggie/dstask/blob/master/integration/next_id_index_test.go)

>  the modify command ignores the ID passed to it and applies the change to every given task. (probably caused by the above)

[Test is here](https://github.com/naggie/dstask/blob/master/integration/modify_test.go#L10), and the file also has the inverse test: modify all tasks in a context if no ID is given.

> search by keyword is broken

[Test is here](https://github.com/naggie/dstask/blob/master/integration/next_search_test.go). We need an additional test for searching notes, I think?

Most of the integration tests have an ID and a +tag variant. We can do more around the other attributes: priority, project.

**Comment by naggie** [comment]
Excellent! 

> Test is here. We need an additional test for searching notes, I think?

Yes we may as well given the search includes the notes.

Having so many tests is great, thanks for taking the time to write them. We can merge with more confidence now.

**Comment by dontlaugh** [comment]
Should we close this and re-open individual issues if needed?

**Comment by naggie** [comment]
ok 👍
