### ISSUE TITLE
Better message when the table is truncated. 

### ISSUE THREAD

**Issue by xm31** [naggie/dstask#67]
When the size of the terminal doesn't permit to display all the tasks, It will be nice to see also the number of displayed tasks.
For now,  only the total number of tasks and the number of rows are shown.

**Comment by naggie** [comment]
Merged, thanks.

**Comment by xm31** [comment]
Great! And thank you for doing this. I was looking for a replacement for task warrior for a while. Now I found it... :)

**Comment by naggie** [comment]
You're welcome, it's nice to have good feedback. Out of interest, what made you change from taskwarrior?

**Comment by xm31** [comment]
The sync part did not go well for me. I tried [taskd](https://wiki.archlinux.org/index.php/Taskd) (not exactly the easiest way to set it up) and hooked git commands (fine until there are conflicts which is very common with recursive daily tasks).

Also, I always felt that it would be nice to be able to add more content to a task.

**Comment by naggie** [comment]
Ah, that reflects my own experience and is why I wrote dstask :+1:
