### ISSUE TITLE
show-resolved shows some tasks with invalid date

### ISSUE THREAD

**Issue by naggie** [naggie/dstask#69]
Since the filtering updates, `show-resolved` is very broken.

1. It shows an invalid date `> Week 1, starting Mon 1 Jan 0001`.
2. It ignores the current context.

**Comment by dontlaugh** [comment]
If you can tell, does the data on disk look correct?

I'll take a look at this after work.

**Comment by naggie** [comment]
Using dstask v0.18 things work correctly, so the data is fine. Thanks!

**Comment by dontlaugh** [comment]
This may be a problem with CommandDone

Should we set the resolved timestamp here?
https://github.com/naggie/dstask/blob/master/commands.go#L104-L110

CommandLog does it correctly
https://github.com/naggie/dstask/blob/master/commands.go#L201

**Comment by dontlaugh** [comment]
A remedy for existing data may be using the unix filesystem mod time as a fall back for a bad resolved date. This mod time should be

* preserved/transferred by git
* _usually_ the same as when the task was resolved, since that is the likely cause of a file being created under the resolved/ folder

https://golang.org/pkg/os/#FileInfo from Stat() can give us this.

**Comment by naggie** [comment]
True -- though I'd rather not rely on the modification date in a prod code path as it's normally wrong. Unless we use it to set the date with a migration. Alternatively we could add a python script to correct the data in `etc/` -- or just leave it, the fall out is minimal.

**Comment by dontlaugh** [comment]
@naggie I was thinking a one-time migration, myself. Migrations are something we might need to come to terms with.

Leave this issue open. I might see what a migration looks like while I check on the context portion of this bug.

Sorry for the grief.

**Comment by naggie** [comment]
True, I guess we can say to run a command as part of the release notes.

> Sorry for the grief.

No problem, bugs are part software dev and you're adding regression tests 👍

**Comment by naggie** [comment]
Perhaps a hidden `dstask migrate` command could be used, and only documented in release notes.

**Comment by dontlaugh** [comment]
That would be a good way to invoke it. We may consider a one-time prompt, for users who miss the notes.

I think the fix I proposed earlier won't be hard to implement, and I won't delay that by insisting that we design a full-blown migration framework. I think we'll want one at some point, but for now a `dstask migrate` command looks good.

If someone experiences this bug, at this stage they will probably come looking here in the repository.

**Comment by dontlaugh** [comment]
So a nice thing about using git: we can run migrations for bug fixes, but not commit. We could leave the directory with changes and ask the user to commit.

This has the drawback of less friendly to users uncomfortable with git, but it is safer.

I'm sketching something out in #72

**Comment by naggie** [comment]
You're right it's less user friendly so I'd rather avoid asking the user to commit. I suppose it depend on how safe the operation is, for 001 it's pretty safe.

**Comment by naggie** [comment]
Also, it seems either I made a mistake about `show-resolved` ignoring context (maybe I was running an older/non release) or it's now fixed. I'll release.

**Comment by naggie** [comment]
Closing, the issue affects a small number of tasks produced by the bug only + the cause is fixed)
