### ISSUE TITLE
git library vs exec.Command

### ISSUE THREAD

**Issue by Dieterbe** [naggie/dstask#76]
Hello,
I see in util.go that dstask currently executes the `git` binary for git operations.
I was wondering if there's any particular opinions on this vs a golang git library such as  [go-git](https://git-scm.com/book/en/v2/Appendix-B%3A-Embedding-Git-in-your-Applications-go-git).
[There seems to be a couple options](https://stackoverflow.com/questions/13532389/git-library-for-go) but the official one, git2go requires cgo so i would stay away from that.

**Comment by dontlaugh** [comment]
This is a tough one.

go-git has some advantages: easy creation of in-memory repository objects could make integration tests quite fast. Also, applications that pull in dstask as a library would benefit from a pure-go git implementation.

However, there might be some rough edges for command line users.

1. I haven't checked on this in a while, but last time I looked, [it did not respect OpenSSH config](https://github.com/src-d/go-git/issues/1220). Has this been fixed? I could not find an issue in the migrated repo.
2. There may be other [git config gotchas](https://github.com/go-git/go-git/issues/76) for command line users.

**Comment by Dieterbe** [comment]
I can't speak to the quality of the git libraries.  Seems safer to stick to exec.Command then and spend our limited FOSS time on things with higher payoff :)

**Comment by naggie** [comment]
The main reason is I use a yubikey, which uses a GnuPG2 [running as an SSH agent](https://callanbryant.co.uk/blog/how-to-get-the-best-out-of-your-yubikey-with-gpg/) and assumed a go-based git library wouldn't be able to use an SSH agent. I didn't research it though. Another reason is I'm super familiar with the git cli and not a library.

That said, it would make porting dstask (using it like a library) to iOS/Android less painful.

**Comment by Dieterbe** [comment]
> porting dstask (using it like a library) to iOS/Android

:heart_eyes: a mobile app would be awesome!

**Comment by naggie** [comment]
Yes it would! Having no smartphone app is a reason quite a lot of people don't use dstask yet. A friend of mine has said he wants to write an iOS and/or Android app for dstask (hello @botto ! )

**Comment by Dieterbe** [comment]
since this was a discussion, not an actual issue, i'm going to close this.
