### ISSUE TITLE
Out of box: Prompt to create ~/.dstask repo with information on remote syncing

### ISSUE THREAD

**Issue by naggie** [naggie/dstask#8]
As discussed in https://github.com/naggie/dstask/issues/7 the out of box experience should be improved to make it a better experience for new users.

- [ ] dstask should prompt the user to create `~/.dstask`
- [ ] ...and explain to the user how remote syncing works
- [ ] dstask should also check git is installed with instructions if not.

**Comment by Dieterbe** [comment]
I think in the vast majority of cases, if the repo doesn't exist already, dstask could automatically create it. or at least prompt the user whether to have dstask create it. related: #76

**Comment by ghistes** [comment]
There is also this slight uglyness when you add your very first task to a newly created repo/dir (I am using the latest realease v0.23.2):

It displays a "fatal" error, that however does not seem to matter...

`dstask add test

Added 1: test
fatal: bad revision 'HEAD'
[master (root-commit) 38ff0bc] Added 1: test
 1 file changed, 11 insertions(+)
 create mode 100644 pending/25c1016c-7d9f-41b7-a321-fb33e56e5d81.yml
`

**Comment by naggie** [comment]
<img width="517" alt="image" src="https://user-images.githubusercontent.com/208440/105100581-58bfca80-5aa5-11eb-8beb-4a1aa0cdf90c.png">


Implemented in master. Also the `help` command now works before initialisation.


@ghistes -- thanks for the report about `fatal: bad revision 'HEAD'` -- I missed that. I happened to fix it in the last big PR.
