### ISSUE TITLE
status of github issues?

### ISSUE THREAD

**Issue by Dieterbe** [naggie/dstask#80]
The readme says:

> As you've probably noticed, I don't use the github issues. Currently I use dstask itself to track dstask bugs in my personal dstask repository. I've left the issues system enabled to allow people to report bugs or request features. As soon as dstask is used by more than a handful of people, I'll probably import the dstask issues to github.

is this still accurate? seems like this is now used by more then a handful of people. would be good to see what the issues are, perhaps we can help with them.

**Comment by naggie** [comment]
You're right, it's not. I've removed it. There are a few issues, I'll transfer the important ones if there are any.

I'll take a look at all the other comments issues you made later tonight if I get time. Thanks for taking a look!
