### ISSUE TITLE
code quality checks in CI

### ISSUE THREAD

**Issue by Dieterbe** [naggie/dstask#86]
it looks like our CI doesn't enforce any code quality checks.
what comes closest is the readme linking to https://goreportcard.com/report/github.com/naggie/dstask
in another project I work on, I have a rich set of [qa checks that enforced](https://github.com/grafana/metrictank/tree/master/scripts/qa) (note, a couple of them are specific to the project) and also some [subjective ones that are not enforced](https://github.com/grafana/metrictank/tree/master/scripts/qa-subjective)

i mention this because there's some interesting examples there to check for spelling mistakes, health of vendor directory, whether everything is correctly formatted, finding unused code, etc.

These scripts may be a bit outdated now though. This space is pretty crowded. https://staticcheck.io/ seems quite solid, there's also gometalinter, go vet (which has both enforceable and more subjective tests), etc.
I'm not sure what's the current best practice. I'm hopeful the community has converged around "one tool to rule them all" ?

**Comment by naggie** [comment]
I'm all for adding code quality checks as part of CI. A `go fmt` check would be a good start. Other than that any other service is fine so long as the rules are sane :-)
