### ISSUE TITLE
Help should talk about dstask command and not task command

### ISSUE THREAD

**Issue by Zejnilovic** [naggie/dstask#9]
The help or README.md should talk about command `dstask` as the original name and not `task` as the one it is suggested to alias to.

**Comment by naggie** [comment]
Good point, corrected. Let me know if I've missed anything.

**Comment by Zejnilovic** [comment]
README.dm screenshot, but I get that might be hard to update.

**Comment by naggie** [comment]
ah yes, I'll just just update it whenever I happen to want to make a new screenshot. I've been meaning to add some for task editing, the project report, task notes, resolved report etc.
