### ISSUE TITLE
dev meeting #1

### ISSUE THREAD

**Issue by Dieterbe** [naggie/dstask#90]
for our first developer video-meeting, I propose the following agenda. I include some questions next to the items, so that we can prepare our thoughts a bit before hand.

## main agenda
* quick intro's :) 
* git integration. commit per file changed or per user invoked modification? file format, encoding of status
* recurring tasks
* syncing with external systems. (taskwarrior, github, others). should they share a common approach? where should the functionality live? how should github syncing work like?

## bonus topics (in case of remaining time, or we push back to next meeting)

* how should the priority system work? are priorities useful at all? what's been your experience in taskwarrior? should they be numeric you can do math with per-project multipliers etc?
* due dates
* subtasks/checklist
* repo layout (exploratory chat. detailed familiarity with standard package layout or similar not required)

**Comment by Dieterbe** [comment]
+ mobile app!

**Comment by naggie** [comment]
# Phone apps

Filesystem, does it make sense?

# Code changes to do

* Filters in taskset constructor -- probably better in methods
* `CmdLine` should be called `Filter` or `Query`. (It just so happens to be a filter from the cmdline
* `TaskSetOpts` is basically the same thing as `CmdLine`/`Filter` but with a sort order. Should be an object containing a cmdline and sort order instead (as discussed previously)


# Non-core things

* Github sync -- separate binary with code using dstask as a library. Within dstask.git for the forseeable future. (sync will be for tracking purposes, be lossy, and probably unidirectional)
* dstask-web could exist in the same way or separate repo, don't mind. https://wails.app/ might a good tool to make dev quicker. DB should not be on web client.


# Recurring tasks

* `RECURRING` type for definitions
* "Virtual" instances that appear on schedule in task list if not already there (generated every invocation) but are not commited to disk until they change
* instances link to parent definition UUID
* Instance UUIDs could be deterministic based on parent uuid and creation date (according to schedule)
* show-recurring is the only way to list definitions, much like show-templates
 

# Priority/urgency

Taskwarrior calculates urgency based on priority and heuristics from weightings gathered from projects/tags. We don't want to make something too complicated or overconfigurable. May change later, for instance considering tasks as part of projects more urgent.


# Philosophy

dstask is opinionated. Should not be over-configurable, should have well defined scope.



---


Thanks everyone, hope I didn't miss anything.

**Comment by Dieterbe** [comment]
that covers pretty much all of it, though i would add:

## Database

We're pretty happy with the "database" (set of text files organized in per status-directories) and consider the format fairly stable. Re #78, we did the experiment of creating a task, syncing to two systems, and on one system changing the status, and on the other adding a note, sync worked fine without conflicts. No one has a strong desire to change the format right now, but we're open to reconsider if we bump into good reasons to.

## Repo layout

yes, we want to organize the code a bit better, isolate separate concerns into separate packages, but not sure yet how.

**Comment by botto** [comment]
I started a chat room on the matrix.org server: https://matrix.to/#/!NPEpBilsAIQPspyKct:matrix.org
