### ISSUE TITLE
show-unorganized seems buggy

### ISSUE THREAD

**Issue by Dieterbe** [naggie/dstask#91]
on one hand, unorganized seems to be about only selecting tasks that have no tags nor project set:

```		if tso.unorganised {
			if len(task.Tags) < 1 && task.Project == "" {
				task.filtered = false
			} else {
				task.filtered = true
			}
			continue
		}
```

On the other hand the command does this:
```
func CommandShowUnorganised(conf Config, ctx, cmdLine CmdLine) error {
	ts, err := NewTaskSet(
		conf.Repo, conf.IDsFile, conf.StateFile,
		WithStatuses(NON_RESOLVED_STATUSES...),
		WithIDs(cmdLine.IDs...),
		WithoutProjects(cmdLine.AntiProjects...),
		WithTags(cmdLine.Tags...),
		WithoutTags(cmdLine.AntiTags...),
		WithUnorganised(),
	)
```
seems to me:
1)  the "Without" options are pointless given the filtering for unorganized we already do.
2) trying to provide tags as the filter doesn't work (a task cannot simultaneously have no tags and also the given task). or is the goal to mean "have no tags except for the ones listed" ? then we'd need to implement that properly, but this doesn't seem useful.

**Comment by naggie** [comment]
> on one hand, unorganized seems to be about only selecting tasks that have no tags nor project set:

Exactly what it should do, I think the filtering refactor changed this accidentally. We should remove the unnecessary filtering.

**Comment by naggie** [comment]
I believe this is no longer a problem now that the filtering changes PR has been merged. Reopen if not 👍
